# Generated by Django 6.0.5 on 2026-06-15 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0234_cablepath_nodes_index'),
        ('netbox_phonenum', '0002_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voipbox_pools', to='dcim.device'),
        ),
    ]
